WCW Automations
blaccsmith/blaccsmith pull request #11
Opened 2022-09-23 00:40 UTC by DarrylBrooks97

[Loom Demo](https://www.loom.com/share/eff3a1f8452b4f09840463b32f6a9c19)

Includes: 
- Checking DB for WCW Topic
- Event creation
- Announcement & Thread creation

2022-09-25 22:59 UTC, gt-codes requested changes

2022-09-25 22:59 UTC, gt-codes commented on src/automations/WCW.ts
> +                'All Water Cooler Wednesday topics have been used ❗️ Add a new one with /update-wcw command',
Minor formatting on the returned message 
```suggestion
                "All Water Cooler Wednesday topics have been used ❗️ Add a new one with `/update-wcw` command",
```

2022-09-25 22:59 UTC, gt-codes commented on src/prisma/schema.prisma
> +}
Add timestamp to this model. I'm just realizing that a lot of the other models don't have `createdAt` and `updatedAt` so make sure all models have these two fields.

```suggestion
  createdAt DateTime      @default(now())
  updatedAt DateTime      @updatedAt
}
```

2022-09-25 22:59 UTC, gt-codes commented on src/constants.ts
> +    MODERATOR_CHANNEL_ID: process.env.MODERATOR_CHANNEL_ID as string,
Did you add this env to Railway @DarrylBrooks97 ?

2022-09-26 22:05 UTC, DarrylBrooks97 commented
Closing this PR. All functionality has moved to PR #12

2022-09-26 22:05 UTC, closed without merging