Allowing moderators to add WCW Topics
blaccsmith/blaccsmith pull request #13
Opened 2022-09-26 23:10 UTC by DarrylBrooks97

2022-09-27 01:42 UTC, blaccsmith requested changes

2022-09-27 01:42 UTC, blaccsmith commented on src/commands/update-wcw.ts
> +    if (!CONSTANTS.MODERATORS.includes(interactionAuthor.id)) {
This isn't maintainable long term. Instead, you can check if the author's roles contains the Moderator role. This means we won't have to redeploy this code whenever Mods change.

2022-09-27 01:42 UTC, blaccsmith commented on src/commands/update-wcw.ts
> +        await Promise.allSettled([
Simple `await` this since there's only one action happening

2022-09-27 01:42 UTC, blaccsmith commented on src/constants.ts
> +    MODERATORS: [process.env.GARY_ID, process.env.GARRETT_ID, process.env.DARRYL_ID],
Not needed – see first comment.
```suggestion
```

2022-09-28 00:46 UTC, Genyus commented
```diff
diff --git a/scripts/sync-kinsta.sh b/scripts/sync-kinsta.sh
index 37f2cd3..c872b68 100755
--- a/scripts/sync-kinsta.sh
+++ b/scripts/sync-kinsta.sh
@@ -20,7 +20,7 @@ declare -A DEV=(
        ["rootdomain"]="frocentric.local"
        ["domain"]="frocentric.local"
        ["url"]="https://frocentric.local"
-       ["discourseurl"]="https://localhost:4200"
+       ["discourseurl"]="https://tech-community.staging.frocentric.io"
 )
 declare -A STAGING=(
        ["bucket"]="s3://froware-staging/uploads"
```

2022-09-28 15:34 UTC, Genyus requested changes
Looks like prisma.schema needs to be reverted

2022-09-28 15:34 UTC, Genyus commented on src/commands/update-wcw.ts
> +}
Don't need to hold up this PR, but would suggest adding the ability to list and remove/edit topics, plus checking for duplicates when creating new ones

2022-09-28 15:34 UTC, Genyus commented on src/lib/addTopic.ts
> +    });
Does this need any error checking?

2022-09-28 15:34 UTC, Genyus commented on src/prisma/schema.prisma
> +
This looks like an accidental, breaking change?

2022-10-03 15:13 UTC, gt-codes commented on src/lib/addTopic.ts
> +    });
In this case, no.

2022-10-03 15:15 UTC, gt-codes commented on src/prisma/schema.prisma
> +
Thanks for catching this! I pushed a fix

2022-10-03 18:29 UTC, gt-codes commented on src/commands/update-wcw.ts
> +}
Just pushed these request

2022-10-04 00:21 UTC, Genyus commented on src/commands/intro.ts
> +            icon: '👋',
Can we get a skin-tone, at least? 👋🏾

2022-10-04 00:25 UTC, Genyus approved these changes
LGTM

2022-10-04 00:31 UTC, blaccsmith approved these changes

2022-10-04 00:32 UTC, merged