Redo new member flow
blaccsmith/blaccsmith pull request #20
Opened 2022-11-15 03:51 UTC by DarrylBrooks97

1. New member accepts community guidelines (Receiving `on-boarding` role)
2. Member is messaged in the `on-boarding` channel with instructions on using `/intro` command
3. Member uses `/intro` command. (`on-boarding` -> `member` role)

Notes: 
- New members (no roles) only have access to community guidelines
- Members with `on-boarding` role can only see `on-boarding`, `welcome`, and `community-guidelines` channels
- Members can see all channels except `on-boarding` channel

2022-11-18 04:20 UTC, Genyus requested changes
Looks good generally, just has a couple stray imports in intro.ts that I'm guessing might've been added before refactoring

2022-11-18 04:20 UTC, Genyus commented on src/commands/intro.ts
> +import { CommandInteraction, CacheType, GuildMember, TextChannel, Message } from 'discord.js';
What are these new imports needed for?

2022-12-01 00:12 UTC, DarrylBrooks97 commented on src/commands/intro.ts
> +import { CommandInteraction, CacheType, GuildMember, TextChannel, Message } from 'discord.js';
Didn't see this. Fixing now

2022-12-01 06:34 UTC, Genyus approved these changes
GTG

2022-12-05 00:51 UTC, merged