Automating GNF message
blaccsmith/blaccsmith pull request #7
Opened 2022-08-27 16:04 UTC by DarrylBrooks97

2022-08-28 22:40 UTC, gt-codes commented on utils/index.ts
> +};
Use the `date-fns` [library](https://date-fns.org/)

2022-09-09 17:41 UTC, DarrylBrooks97 commented
POC: https://www.loom.com/share/42f39c1edf464d56b13cf4ebf7aff5ca

2022-09-16 17:27 UTC, gt-codes requested changes
I love the loom! Much appreciated. Just accept the `yarn.lock` suggestion and it's GTG

2022-09-16 17:27 UTC, gt-codes commented on yarn.lock
> +>>>>>>> 6b886c9ae2cc09e3f01722c1821a98467613c176
```suggestion
date-fns@^2.29.2:
  version "2.29.2"
  resolved "https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.2.tgz#0d4b3d0f3dff0f920820a070920f0d9662c51931"
  integrity sha512-0VNbwmWJDS/G3ySwFSJA3ayhbURMTJLtwM2DTxf9CWondCnh6DTNlO9JgRSq6ibf4eD0lfMJNBxUdEAHHix+bA==

debug@^4.1.1, debug@^4.3.2:
```

2022-09-16 19:04 UTC, merged